grails-app/domain/gestionimagenes/multimedia/MultimediaImagen.groovy
package gestionimagenes.multimedia

abstract class MultimediaImagen extends Multimedia {
	
	static transients = ['ruta']

	private static String ruta = ""
	
	String imagen
	
    static constraints = {
		imagen nullable:true, blank:true
    }
	
	def afterDelete() {
		//Borrar el fichero del sistema de ficheros
		println "MultimediaImagen - afterDelete()"
		println this.imagen
				
		if (this.imagen != "") {
			if (!fileUploadService.removeFile(this.imagen, this.obtenerRuta())) {
				println "NO SE HA BORRADO EL FICHERO: " + this.obtenerRuta() + this.imagen
			}
		}
	}
	
	String toString() {
		return this.imagen
	}
	
	public abstract String obtenerRuta()
	
	public abstract String getTipo()
	
	public abstract getContenedor()
	
}

grails-app/controllers/gestionimagenes/multimedia/MultimediaImagenController.groovy
package gestionimagenes.multimedia

import gestionimagenes.FileUploadService
import gestionimagenes.PropiedadImagen

class MultimediaImagenController {

	FileUploadService fileUploadService

	def viewImage(){
		println "MultimediaImagenController viewImage: " + params.id
		if (params.id != "null") {
			MultimediaImagen multimediaImagenInstance = MultimediaImagen.get((params.id) as Long)
			//println propiedadImagenInstance.imagen
			println fileUploadService.obtenerRutaAbsolutaMultimedia() + multimediaImagenInstance.obtenerRuta() + multimediaImagenInstance.imagen
			def file = new File(fileUploadService.obtenerRutaAbsolutaMultimedia() + multimediaImagenInstance.obtenerRuta() + multimediaImagenInstance.imagen)
			def img = file.bytes
			response.contentType = 'image/png' // or the appropriate image content type
			response.outputStream << img
			response.outputStream.flush()
		}
	}


}

grails-app/views/multimediaImagen/_formImagenPrincipal.gsp
<g:if test="${contenedor.id}">
	<g:if test="${flash.messageImagenPrincipal}">
		<div class="row">
			<div class="col-md-12">		
				<bootstrap:alert class="alert alert-info">${flash.messageImagenPrincipal}</bootstrap:alert>
			</div>
		</div>
	</g:if>
	
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
				<div class="col-sm-2 control-label">
					<label for="imagenPrincipalForm"> <g:message code="contenedor.imagenPrincipal.label"
							default="Imagen Principal" />
					</label>
				</div>
				<div class="col-sm-7">
					<input type="file" name="imagenPrincipalForm" id="imagenPrincipalForm" accept="image/png, image/jpg, image/jpeg"
						onchange="validarFormatoImagenes(this);$('#imagenPrincipalFormVisible').val($(this).val().split('\\').pop());"
						class="hidden" />

					<div class="input-group">
						<span class="input-group-btn"> <a class="btn btn-default"
							onclick="$('#imagenPrincipalForm').click();" title="Seleccionar imagen principal">Sel.</a>
						</span> 
						<input type="text" name="imagenPrincipalFormVisible" id="imagenPrincipalFormVisible"
							class="form-control" disabled /> 
						<span class="input-group-btn"> <g:actionSubmit
								value="${message(code:'default.add.label', args: [' '])}" action="addImagenPrincipal"
								class="btn btn-primary"
								title="${message(code:'default.add.label', args: [message(code: 'multimediaImagenPrincipal.label', default: 'Imagen principal')])}" />
						</span>
					</div>
					<p class="help-block">
						<g:message code="multimediaImagenPrincipal.ayudaSubida.label" default="Ficheros .jpg o .png de un máximo de 512KB" />												
					</p>
				</div>
				<div class="col-sm-3">
					<g:if test="${contenedor.imagenPrincipal}">
						<div class="thumbnail">
							<img
								src="<g:createLink controller="multimediaImagen" action="viewImage" 
							params="[id:"${contenedor.imagenPrincipal.id}" ]"/>"
							class="img-responsive img-rounded"/>
							<div class="caption text-center">
								<small><g:message code="contenedor.imagenPrincipal.label" default="Imagen Principal" /></small>
								<g:link controller="${contenedor.imagenPrincipal.getClass().simpleName}" action="delete"
									id="${contenedor.imagenPrincipal.id}" class="btn btn-xs btn-danger pull-right"
									onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
									<span class="glyphicon glyphicon-remove"></span>
     							Eliminar
     					</g:link>
							</div>
						</div>
					</g:if>
				</div>
			</div>
		</div>
	</div>
</g:if>

grails-app/views/multimediaImagen/_formImagenes.gsp
<g:if test="${contenedor.id}">
	<div class="panel panel-default" id="panelImagenes">
		<div class="panel-heading">
			<g:message code="multimediaImagenes.label" default="Imagenes" />
			<span class="badge"> ${contenedor?.imagenes?.size()}</span>
			<a data-toggle="collapse" data-parent="#accordion" href="#addImagen" class="btn btn-default btn-xs pull-right"
				title="${message(code:'default.add.label', args: [message(code: 'multimediaImagen.label', default: 'Imagen')])}">
				<i class="glyphicon glyphicon-plus"></i>
			</a>
		</div>
		<div class="panel-body">
			<g:if test="${flash.messageImage}">				
				<bootstrap:alert class="alert alert-info">${flash.messageImage}</bootstrap:alert>
			</g:if>
			
			<div id="addImagen" class="panel-collapse collapse">
				<g:if test="${contenedor.puedeAñadirNuevaImagen()}">
					<div class="row">
						<div class="col-md-12">							
							<div class="well well-sm">
								<div class="form-group">
									<div class="col-sm-3 control-label">
										<label for="imagen"> ${message(code: 'default.add.label', args: [message(code: 'multimediaImagen.label', default: 'Imagen')])}
										</label>
									</div>
									<div class="col-sm-9">
										<input type="file" name="imagenForm" id="imagenForm" accept="image/png, image/jpg, image/jpeg"
											onchange="validarFormatoImagenes(this);$('#imagenFormVisible').val($(this).val().split('\\').pop());"
											class="hidden" />
	
										<div class="input-group">
											<span class="input-group-btn"> <a class="btn btn-default" onclick="$('#imagenForm').click();"
												title="Seleccionar nueva imagen">Sel.</a>
											</span> 
											<input type="text" name="imagenFormVisible" id="imagenFormVisible" class="form-control" disabled /> 
											
											<span class="input-group-btn"> <g:actionSubmit
													value="${message(code:'default.add.label', args: [' '])}" action="addImagen"
													class="btn btn-primary"
													title="${message(code:'default.add.label', args: [message(code: 'multimediaImagen.label', default: 'Imagen')])}" />
											</span>
										</div>
	
										<p class="help-block">									
											<g:message code="multimediaImagenes.ayudaSubida.label" default="Ficheros .jpg o .png de un máximo de 512KB" />
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</g:if>
				<g:else>
					<div class="well well-sm">					
						<g:message code="multimediaImagenes.maximoAlcanzado.label" default="Máximo de imágenes alcanzado" />
					</div>
				</g:else>
			</div>

			<g:if test="${contenedor?.imagenes?.size()>0}">
				<div class="row">
					<% int j = 1; %>
					<g:each in="${contenedor?.imagenes?.sort{it.id}}" var="i">
						<div class="col-xs-6 col-sm-4 col-md-3">
							<div class="thumbnail">
								<img src="<g:createLink controller='multimediaImagen' action='viewImage' params='[id:" ${i.id} "]' />"
									class="img-responsive img-rounded" />

								<div class="caption">
									<p>
										<span class="badge">
											${j} <% j++; %>
										</span>
										${i.nombre }
									</p>
									<p class="text-center">
										<small>${i.tamanoKB }KB</small><br>
										<small><g:formatDate format="yyyy-MM-dd HH:mm:ss a" date="${i.dateCreated}"/></small>
									</p>

									<g:link controller="${i.getClass().simpleName}" action="delete" id="${i.id}"
										class="btn btn-xs btn-danger pull-right"
										onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
										<span class="glyphicon glyphicon-remove"></span>Eliminar
     										</g:link>
									<br>
								</div>
							</div>
						</div>
					</g:each>
				</div>
			</g:if>			
		</div>
	</div>
</g:if>

grails-app/views/multimediaImagen/_formPlanos.gsp
<g:if test="${contenedor.id}">
	<div class="panel panel-default" id="panelPlanos">
		<div class="panel-heading">
			<g:message code="multimediaPlanos.label" default="Planos" />
			<span class="badge">
				${contenedor?.planos?.size()}
			</span> <a data-toggle="collapse" data-parent="#accordion" href="#addPlano"
				class="btn btn-default btn-xs pull-right"
				title="${message(code:'default.add.label', args: [message(code: 'multimediaPlano.label', default: 'Plano')])}">
				<i class="glyphicon glyphicon-plus"></i>
			</a>
		</div>
		<div class="panel-body">
			<g:if test="${flash.messagePlano}">
				<bootstrap:alert class="alert alert-info">
					${flash.messagePlano}
				</bootstrap:alert>
			</g:if>

			<div id="addPlano" class="panel-collapse collapse">
				<g:if test="${contenedor.puedeAñadirNuevoPlano()}">
					<div class="row">
						<div class="col-md-12">							
							<div class="well well-sm">
								<div class="form-group">
									<div class="col-sm-3 control-label">
										<label> ${message(code: 'default.add.label', args: [message(code: 'multimediaPlano.label', default: 'Plano')])}
										</label>
									</div>
									<div class="col-sm-9">
										<input type="file" name="planoForm" id="planoForm" accept="image/png, image/jpg, image/jpeg"
											onchange="validarFormatoImagenes(this);$('#planoFormVisible').val($(this).val().split('\\').pop());"
											class="hidden" />

										<div class="input-group">
											<span class="input-group-btn"> <a class="btn btn-default" onclick="$('#planoForm').click();"
												title="Seleccionar nuevo plano">Sel.</a>
											</span> <input type="text" name="planoFormVisible" id="planoFormVisible" class="form-control" disabled />
											<span class="input-group-btn"> <g:actionSubmit
													value="${message(code:'default.add.label', args: [' '])}" action="addPlano"
													class="btn btn-primary"
													title="${message(code:'default.add.label', args: [message(code: 'multimediaPlano.label', default: 'Plano')])}" />
											</span>
										</div>

										<p class="help-block">
											<g:message code="multimediaPlanos.ayudaSubida.label"
												default="Ficheros .jpg o .png de un máximo de 512KB" />
										</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</g:if>
				<g:else>
					<div class="well well-sm">
						<g:message code="multimediaPlanos.maximoAlcanzado.label" default="Máximo de planos alcanzado" />
					</div>
				</g:else>
			</div>
				
			<g:if test="${contenedor?.planos?.size()>0}">
				<div class="row">
					<% int j = 1; %>
					<g:each in="${contenedor?.planos?.sort{it.id}}" var="i">
						<div class="col-xs-6 col-sm-4 col-md-3">						
							<div class="thumbnail">																
								<img src="<g:createLink controller='multimediaImagen' action='viewImage' params='[id:"${i.id}"]' />"
									 class="img-responsive  img-rounded" alt="Imagen" /> 								
								<div class="caption">
									<p><span class="badge">${j} <% j++; %></span>${i.nombre }</p>
									<p class="text-center">
										<small>${i.tamanoKB }KB</small><br> 
										<small><g:formatDate format="yyyy-MM-dd HH:mm:ss a" date="${i.dateCreated}" /></small>
									</p>

									<g:link controller="${i.getClass().simpleName}" action="delete" id="${i.id}"
										class="btn btn-xs btn-danger pull-right"
										onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');">
										<span class="glyphicon glyphicon-remove"></span>Eliminar
			     					</g:link>
									<br>
								</div>
							</div>
						</div>
					</g:each>
				</div>
			</g:if>
		</div>
	</div>
</g:if>

grails-app/views/multimediaImagen/_showImagenPrincipal.gsp
<g:if test="${contenedor?.imagenPrincipal}">
	<div class="panel panel-default">
		<div class="panel-heading">
			<g:message code="propiedad.imagenPrincipal.label" default="Imagen Principal" />						
		</div>
		<div class="panel-body text-center">					
			
			<span class="property-value" aria-labelledby="imagenPrincipal-label">
					<img src="<g:createLink controller="multimediaImagen" action="viewImage" params="[id:"${contenedor.imagenPrincipal.id}" ]"/>"
						width="150px" class="imagenSobra img-rounded"/>
			</span>
		</div>
	</div>
</g:if>

grails-app/views/multimediaImagen/_showImagenesYPlanos.gsp
<g:if test="${contenedor?.imagenes || contenedor?.planos}">
	<div class="panel panel-default">
		<div class="panel-heading">
			<g:message code="multimediaImagenes.label" default="Imagenes" />
			<span class="badge">${contenedor?.imagenes?.size() + contenedor?.planos?.size()}</span>			
		</div>
		<div class="panel-body text-center">			
			<div class="coverimg">
				<g:if test="${contenedor?.imagenes?.size()>0}">
					<h2><g:message code="multimediaImagenes.label" default="Imagenes" /></h2>
					<g:each in="${contenedor?.imagenes?.sort{it.id}}" var="i">
						<a href="#" onclick="e.preventDefault();"> <img data-gallery="my-gallery" class="imagenSobra img-rounded"
							src="<g:createLink controller='multimediaImagen' action='viewImage' params='[id:" ${i.id} "]' />"
							width="150px"/>
						</a>
					</g:each>
				</g:if>
				
				<g:if test="${contenedor?.planos?.size()>0}">
					<h2><g:message code="multimediaPlanos.label" default="Planos" /></h2>
					<g:each in="${contenedor?.planos?.sort{it.id}}" var="i">
						<a href="#" onclick="e.preventDefault();"> <img data-gallery="my-gallery" class="imagenSobra img-rounded"
							src="<g:createLink controller='multimediaImagen' action='viewImage' params='[id:" ${i.id} "]' />"
							width="150px"/>
						</a>
					</g:each>
				</g:if>
			</div>
		</div>
	</div>
	
	<script>
		inicializarGaleriaImagenes();
	</script>
</g:if>