grails-app/domain/gestionimagenes/Entidad.groovy
package gestionimagenes

import gestionImagenes.multimedia.iMultimedia;

class Entidad implements iMultimedia {
	
	String nombre
	
	EntidadImagenPrincipal imagenPrincipal
	
	static hasMany = [documentos:EntidadDocumento]

    static constraints = {
		nombre nullable:false, blank:false
		imagenPrincipal nullable:true, blank:true
		documentos nullable:true, blank:true
    }

	@Override
	public boolean puedeAñadirNuevaImagen() {
		// Sin limites
		return true;
	}
	@Override
	public boolean puedeAñadirNuevoPlano() {
		// Entidades no tienen planos
		return false;
	}
	@Override
	public boolean puedeAñadirNuevoDocumento() {
		//Sin limites
		return true;
	}
	@Override
	public boolean puedeAñadirNuevoVideo() {
		//Sin limites
		return true;
	}}

grails-app/controllers/gestionimagenes/EntidadController.groovy
package gestionimagenes

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional


@Transactional(readOnly = true)
class EntidadController {

    //static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Entidad.list(params), model:[entidadInstanceCount: Entidad.count()]
    }

    def show(Entidad entidadInstance) {
        respond entidadInstance
    }

    def create() {
        respond new Entidad(params)
    }

    @Transactional
    def save(Entidad entidadInstance) {
        if (entidadInstance == null) {
            notFound()
            return
        }

        if (entidadInstance.hasErrors()) {
            respond entidadInstance.errors, view:'create'
            return
        }

        entidadInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.created.message', args: [message(code: 'entidad.label', default: 'Entidad'), entidadInstance.id])
                redirect entidadInstance
            }
            '*' { respond entidadInstance, [status: CREATED] }
        }
    }

    def edit(Entidad entidadInstance) {
        respond entidadInstance
    }

    @Transactional
    def update(Entidad entidadInstance) {
        if (entidadInstance == null) {
            notFound()
            return
        }

        if (entidadInstance.hasErrors()) {
            respond entidadInstance.errors, view:'edit'
            return
        }

        entidadInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Entidad.label', default: 'Entidad'), entidadInstance.id])
                redirect entidadInstance
            }
            '*'{ respond entidadInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Entidad entidadInstance) {

        if (entidadInstance == null) {
            notFound()
            return
        }

        entidadInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Entidad.label', default: 'Entidad'), entidadInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'entidad.label', default: 'Entidad'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
	
	@Transactional
	def addImagenPrincipal() {
		forward controller: 'entidadImagenPrincipal', action:'create', model:[imagenPrincipalForm:request.getFile('imagenPrincipalForm')], params:params
	}
		
//	@Transactional
//	def addImagen() {
//		forward controller: 'entidadImagen', action:'create', model:[imagenForm:request.getFile('imagenForm')], params:params
//	}
	
//	@Transactional
//	def addPlano() {
//		forward controller: 'propiedadPlano', action:'create', model:[planoForm:request.getFile('planoForm')], params:params
//	}
	
	@Transactional
	def addDocumento() {
		forward controller: 'entidadDocumento', action:'create', model:[documentoForm:request.getFile('documentoForm')], params:params
	}
		
//	@Transactional
//	def addVideo() {
//		forward controller: 'entidadVideo', action:'create', params:params
//	}
}

grails-app/views/entidad/_form.gsp
<%@ page import="gestionimagenes.Entidad" %>

<div class="form-group">
	<div class="col-sm-2 control-label text-danger">
		<label for="nombre">
			<g:message code="entidad.nombre.label" default="Nombre" />
			<span class="required-indicator">*</span>
		</label>
	</div>
	<div class="col-sm-10">
		<g:textField name="nombre" class="form-control" value="${entidadInstance?.nombre}"/>
	</div>
</div>

<g:render template="/multimediaImagen/formImagenPrincipal" bean="${entidadInstance}" var="contenedor" />

<g:render template="/multimediaDocumento/formDocumentos" bean="${entidadInstance}" var="contenedor" />

grails-app/views/entidad/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'entidad.label', default: 'Entidad')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-entidad" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-entidad" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${entidadInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${entidadInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:entidadInstance, action:'save']" >				
				<g:render template="form"/>		
				<br>
				<br>
				<br>		
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/entidad/edit.gsp
<%@ page import="gestionimagenes.Entidad" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'entidad.label', default: 'Entidad')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-entidad" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-entidad" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${entidadInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${entidadInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:entidadInstance, action:'update']" method="PUT" enctype="multipart/form-data" class="form-horizontal" >
				<g:hiddenField name="version" value="${entidadInstance?.version}" />				
				<g:render template="form"/>				
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/entidad/index.gsp
<%@ page import="gestionimagenes.Entidad" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'entidad.label', default: 'Entidad')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-entidad" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-entidad" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="nombre" title="${message(code: 'entidad.nombre.label', default: 'Nombre')}" />
						<g:sortableColumn property="imagenPrincipal" title="${message(code: 'propiedad.imagenPrincipal.label', default: 'Imagen Principal')}" />
						<th class="text-center">Documentos</th>
					</tr>
				</thead>
				<tbody>
				<g:each in="${entidadInstanceList}" status="i" var="entidadInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${entidadInstance.id}">${fieldValue(bean: entidadInstance, field: "nombre")}</g:link></td>
						<td>
							<g:if test="${ entidadInstance.imagenPrincipal }">
	 							<img src="<g:createLink controller="multimediaImagen" action="viewImage" params="[id:"${entidadInstance.imagenPrincipal.id}"]"/>" 
	 								height="40px"/>
	 						</g:if>
						</td>
						<td class="text-center">${ entidadInstance.documentos.size() }</td>
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${entidadInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/entidad/show.gsp
<%@ page import="gestionimagenes.Entidad" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'entidad.label', default: 'Entidad')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-entidad" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-entidad" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list entidad">
			
				<g:if test="${entidadInstance?.nombre}">
				<li class="fieldcontain">
					<span id="nombre-label" class="property-label"><g:message code="entidad.nombre.label" default="Nombre" /></span>					
					<span class="property-value" aria-labelledby="nombre-label"><g:fieldValue bean="${entidadInstance}" field="nombre"/></span>					
				</li>
				</g:if>										
			</ol>
			
			<g:render template="/multimediaImagen/showImagenPrincipal" bean="${entidadInstance}" var="contenedor" />
			
			<g:render template="/multimediaDocumento/showDocumentos" bean="${entidadInstance}" var="contenedor" />	
			
			<g:form url="[resource:entidadInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${entidadInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>