grails-app/domain/gestionimagenes/Propiedad.groovy
package gestionimagenes

import gestionImagenes.multimedia.iMultimedia
import gestionImagenes.Utiles

class Propiedad implements iMultimedia {		
	
	String nombre
	
	PropiedadImagenPrincipal imagenPrincipal
	
	static hasMany = [imagenes:PropiedadImagen, planos:PropiedadPlano, documentos:PropiedadDocumento, videos:PropiedadVideo]

    static constraints = {
		nombre nullable:false, blank:false
		imagenPrincipal nullable:true, blank:true
		imagenes nullable:true, blank:true
		planos nullable:true, blank:true
		documentos nullable:true, blank:true
		videos nullable:true, blank:true
    }
	
	String toString() {
		return this.nombre
	}
	
	@Override
	boolean puedeAñadirNuevaImagen() {
		return Utiles.obtenerConfig().maximoImagenesPorPropiedad > this.imagenes.size()		
	}
	
	@Override
	boolean puedeAñadirNuevoPlano() {
		return Utiles.obtenerConfig().maximoImagenesPorPropiedad > this.planos.size()
	}
	
	@Override
	boolean puedeAñadirNuevoDocumento() {		
		return Utiles.obtenerConfig().maximoDocumentosPorPropiedad > this.documentos.size()
	}

	@Override
	public boolean puedeAñadirNuevoVideo() {
		//Sin limites
		return true;
	}
}

grails-app/controllers/gestionimagenes/PropiedadController.groovy
package gestionimagenes

import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class PropiedadController {
	//def scaffold = true		
	
    static allowedMethods = [save: "POST", update: "POST", delete: "DELETE"]
	
	FileUploadService fileUploadService		

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Propiedad.list(params), model:[propiedadInstanceCount: Propiedad.count()]
    }

    def show(Propiedad propiedadInstance) {
        respond propiedadInstance
    }

    def create() {
        respond new Propiedad(params)
    }

    @Transactional
    def save(Propiedad propiedadInstance) {
        if (propiedadInstance == null) {
            notFound()
            return
        }

        if (propiedadInstance.hasErrors()) {
            respond propiedadInstance.errors, view:'create'
            return
		}

		if(propiedadInstance.save(flush:true)) {		
			request.withFormat {
				form multipartForm {
					flash.message = message(code: 'default.created.message', args: [message(code: 'propiedad.label', default: 'Propiedad'), propiedadInstance.id])										
					redirect propiedadInstance
				}
				'*' { respond propiedadInstance, [status: CREATED] }
			}
		}       
    }

    def edit(Propiedad propiedadInstance) {
        respond propiedadInstance
    }

    @Transactional
    def update(Propiedad propiedadInstance) {
        if (propiedadInstance == null) {
            notFound()
            return
        }

        if (propiedadInstance.hasErrors()) {
            respond propiedadInstance.errors, view:'edit'
            return
        }
			
       if(propiedadInstance.save(flush:true)) {						
			 request.withFormat {
				form multipartForm {
					flash.message = message(code: 'default.updated.message', args: [message(code: 'Propiedad.label', default: 'Propiedad'), propiedadInstance.id])
					redirect propiedadInstance
				}
				'*'{ respond propiedadInstance, [status: OK] }
			}
		}       
    }

    @Transactional
    def delete(Propiedad propiedadInstance) {
		println ("delete")
        if (propiedadInstance == null) {
            notFound()
            return
        }
		
		propiedadInstance.delete(flush:true)
				
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Propiedad.label', default: 'Propiedad'), propiedadInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'propiedad.label', default: 'Propiedad'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }

	@Transactional
	def addImagenPrincipal() {
		forward controller: 'propiedadImagenPrincipal', action:'create', model:[imagenPrincipalForm:request.getFile('imagenPrincipalForm')], params:params
	}
		
	@Transactional
	def addImagen() {
		forward controller: 'propiedadImagen', action:'create', model:[imagenForm:request.getFile('imagenForm')], params:params
	}
	
	@Transactional
	def addPlano() {				
		forward controller: 'propiedadPlano', action:'create', model:[planoForm:request.getFile('planoForm')], params:params				
	}
	
	@Transactional
	def addDocumento() {				
		forward controller: 'propiedadDocumento', action:'create', model:[documentoForm:request.getFile('documentoForm')], params:params
	}
		
	@Transactional
	def addVideo() {				
		forward controller: 'propiedadVideo', action:'create', params:params				
	}
}

grails-app/views/propiedad/_form.gsp
<%@ page import="gestionimagenes.Propiedad" %>


<div class="form-group">
	<div class="col-sm-2 control-label text-danger">
		<label for="nombre">
			<g:message code="propiedad.nombre.label" default="Nombre" />
			<span class="required-indicator">*</span>
		</label>
	</div>
	<div class="col-sm-10">
		<g:textField name="nombre" class="form-control" value="${propiedadInstance?.nombre}"/>
	</div>
</div>
 
<g:render template="/multimediaImagen/formImagenPrincipal" bean="${propiedadInstance}" var="contenedor" />

<g:render template="/multimediaImagen/formImagenes" bean="${propiedadInstance}" var="contenedor" />

<g:render template="/multimediaImagen/formPlanos" bean="${propiedadInstance}" var="contenedor" />

<g:render template="/multimediaDocumento/formDocumentos" bean="${propiedadInstance}" var="contenedor" />

<g:render template="/multimediaVideo/formVideos" bean="${propiedadInstance}" var="contenedor" />
 

grails-app/views/propiedad/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'propiedad.label', default: 'Propiedad')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-propiedad" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-propiedad" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${propiedadInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${propiedadInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:propiedadInstance, action:'save']" enctype="multipart/form-data" >				
				<g:render template="form"/>
				<br>
				<br>
				<br>				
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/propiedad/edit.gsp
<%@ page import="gestionimagenes.Propiedad" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'propiedad.label', default: 'Propiedad')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-propiedad" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-propiedad" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${propiedadInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${propiedadInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:propiedadInstance, action:'update']" method="PUT" enctype="multipart/form-data" class="form-horizontal">
				<g:hiddenField name="version" value="${propiedadInstance?.version}" />
				
					<g:render template="form"/>
				
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/propiedad/index.gsp
<%@ page import="gestionimagenes.Propiedad" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'propiedad.label', default: 'Propiedad')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-propiedad" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-propiedad" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="nombre" title="${message(code: 'propiedad.nombre.label', default: 'Nombre')}" />
					
						<g:sortableColumn property="imagenPrincipal" title="${message(code: 'propiedad.imagenPrincipal.label', default: 'Imagen Principal')}" />						
						<th class="text-center">Imagenes</th>
						<th class="text-center">Planos</th>
						<th class="text-center">Documentos</th>
						<th class="text-center">Videos</th>
					</tr>
				</thead>
				<tbody>
				<g:each in="${propiedadInstanceList}" status="i" var="propiedadInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${propiedadInstance.id}">${fieldValue(bean: propiedadInstance, field: "nombre")}</g:link></td>
					
						<td>
							<g:if test="${ propiedadInstance.imagenPrincipal }">
	 							<img src="<g:createLink controller="multimediaImagen" action="viewImage" params="[id:"${propiedadInstance.imagenPrincipal.id}"]"/>" 
	 								height="40px"/>
	 						</g:if>
						</td>
						<td class="text-center">${ propiedadInstance.imagenes.size() }</td>
						<td class="text-center">${ propiedadInstance.planos.size() }</td>
						<td class="text-center">${ propiedadInstance.documentos.size() }</td>
						<td class="text-center">${ propiedadInstance.videos.size() }</td>
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${propiedadInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/propiedad/show.gsp
<%@ page import="gestionimagenes.Propiedad" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'propiedad.label', default: 'Propiedad')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
		<asset:stylesheet src="jquery-gallery.css"/>
		<asset:javascript src="jquery-gallery.js"/>
	</head>
	<body>
		<a href="#show-propiedad" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-propiedad" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list propiedad">
			
				<g:if test="${propiedadInstance?.nombre}">
					<li class="fieldcontain">
						<span id="nombre-label" class="property-label"><g:message code="propiedad.nombre.label" default="Nombre" /></span>
						
						<span class="property-value" aria-labelledby="nombre-label"><g:fieldValue bean="${propiedadInstance}" field="nombre"/></span>	
					</li>
				</g:if>																																												
			</ol>
						
			<g:render template="/multimediaImagen/showImagenPrincipal" bean="${propiedadInstance}" var="contenedor" />
			
			<g:render template="/multimediaImagen/showImagenesYPlanos" bean="${propiedadInstance}" var="contenedor" />
			
			<g:render template="/multimediaDocumento/showDocumentos" bean="${propiedadInstance}" var="contenedor" />	
			
			<g:render template="/multimediaVideo/showVideos" bean="${propiedadInstance}" var="contenedor" />						
			
			<g:form url="[resource:propiedadInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${propiedadInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>		
	</body>
</html>